In [1]:
import pandas as pd

In [2]:
import numpy as np

In [210]:
ego = pd.read_csv('2018-12-04-10-59-21-ego-car-odometry.csv')
ego = ego.rename(index=str, columns={"header.stamp.secs": "s", "header.stamp.nsecs": "ns", "pose.position":"pos", "pose.orientation":"ori"})
ego.pos = ego.apply(lambda x: list(map(float, x.pos[1:-1].split(','))), axis=1)
ego.ori = ego.apply(lambda x: list(map(float, x.ori[1:-1].split(','))), axis=1)
ego.s = list(map(int, ego['s']))
ego.ns = list(map(int, ego['ns']))
ego.time = ego.apply(lambda x: x.s - ego.s[0] + x.ns/1e9 , axis=1)
ego = ego.drop(['s','ns','pose_covariance'],axis=1)
ego.head()

,time,pos,ori
0,0.3089,"[466538.1585880562, 4431892.497966345, 22.7692...","[-0.0021358155166993653, 0.006099189717021143,..."
1,0.3289,"[466538.0276850064, 4431892.170371138, 22.7200...","[-0.0021994248559512684, 0.005927062896605702,..."
2,0.3489,"[466537.9111474166, 4431891.8743251, 22.723066...","[-0.0022718529019892584, 0.005932374300024205,..."
3,0.3689,"[466537.7945988823, 4431891.578404029, 22.7261...","[-0.002366978735537332, 0.005933839865256696, ..."
4,0.3889,"[466537.6780530546, 4431891.282588708, 22.7292...","[-0.0024391829553945575, 0.005872257110512698,..."

In [211]:
ego[-10:]

,time,pos,ori
19308,386.4598,"[459979.1232960499, 4432239.480684999, 33.0002...","[-0.01639999479714928, -0.006023222258428381, ..."
19309,386.4798,"[459978.8355845532, 4432239.530905398, 32.9906...","[-0.01638030843911749, -0.0059804729551082665,..."
19310,386.4998,"[459978.5480333385, 4432239.581159787, 32.9812...","[-0.01640650157568687, -0.005898400821252086, ..."
19311,386.5198,"[459978.2606274012, 4432239.631397461, 32.9721...","[-0.016542389403416267, -0.006013314976678146,..."
19312,386.5398,"[459977.973454423, 4432239.681702007, 32.96321...","[-0.016533584677238863, -0.005955366761968294,..."
19313,386.5598,"[459977.6864359232, 4432239.73201143, 32.95437...","[-0.016605870678117078, -0.006158901480259981,..."
19314,386.5798,"[459977.3996583915, 4432239.78223372, 32.94563...","[-0.01659337151205556, -0.006187404842833934, ..."
19315,386.5998,"[459977.1130238078, 4432239.832458037, 32.9369...","[-0.016632792973656958, -0.006256804684544537,..."
19316,386.6198,"[459976.8265392894, 4432239.882581363, 32.9283...","[-0.01665783637533421, -0.006300297977490051, ..."
19317,386.6398,"[459976.54025150405, 4432239.932707434, 32.919...","[-0.0167310809297561, -0.006376499001342216, 0..."

In [191]:
ego.pos = ego.pos.apply(np.array)
ego.ori = ego.ori.apply(np.array)
ego.pos = ego.pos.apply(lambda x: x - ego.pos[0])

In [209]:
ego.pos

0                                          [0.0, 0.0, 0.0]
1        [-0.130903049838, -0.32759520784, -0.049163642...
2        [-0.247440639592, -0.623641245067, -0.04613907...
3          [-0.3639891739, -0.9195623165, -0.043035143344]
4        [-0.48053500161, -1.21537763719, -0.0399116943...
5        [-0.597084980458, -1.51105224807, -0.036742186...
6        [-0.713620317925, -1.80661811773, -0.033499302...
7        [-0.830139770231, -2.10208495148, -0.030281830...
8        [-0.946645141172, -2.39743977971, -0.027129554...
9        [-1.06311662711, -2.69270974211, -0.0241050836...
10       [-1.17955260351, -2.98785798065, -0.0211523471...
11       [-1.2959812734, -3.28292831592, -0.0182080554237]
12       [-1.41240716737, -3.57790915202, -0.0153700024...
13        [-1.52883471007, -3.87277368642, -0.01267529293]
14       [-1.66003006499, -4.20057001151, -0.0628348239...
15       [-1.75729461579, -4.44692093879, -0.0245200773...
16       [-1.87344694603, -4.74088088609, -0.0217874479...
17       [-1.9895682105, -5.03479590826, -0.0191932781985]
18       [-2.10565236059, -5.32863253076, -0.0165903066...
19       [-2.22171364597, -5.62236765586, -0.013885567307]
20       [-2.33777519886, -5.91605592333, -0.0111794535...
21       [-2.45386235102, -6.20964210201, -0.0085015736...
22       [-2.56994089077, -6.50314581767, -0.0058361112...
23       [-2.68604416575, -6.79659011681, -0.0032074818...
24       [-2.8021159757, -7.08999978751, -0.00056006943...
25       [-2.91822003352, -7.38337180484, 0.00216364867...
26       [-3.04892728955, -7.70692190155, -0.0452591776...
27       [-3.16514895146, -8.00033747684, -0.0427159151...
28       [-3.28135407617, -8.2937002359, -0.0401654377579]
29       [-3.39753089036, -8.58704738505, -0.0376900786...
                               ...
19288       [-6553.26955668, 345.974197637, 10.4311746997]
19289       [-6553.55908316, 346.024991404, 10.4223270026]
19290        [-6553.84859948, 346.075887697, 10.413705254]
19291       [-6554.13816512, 346.126762669, 10.4051834772]
19292        [-6554.42773341, 346.17762319, 10.3968814875]
19293        [-6554.71730829, 346.228542473, 10.388803855]
19294       [-6555.00692041, 346.279400359, 10.3807098096]
19295        [-6555.29649513, 346.330176708, 10.372754084]
19296       [-6555.58608145, 346.380907502, 10.3646667104]
19297       [-6555.87565358, 346.431506406, 10.3562833742]
19298       [-6556.16517486, 346.482009598, 10.3475804456]
19299       [-6556.45461857, 346.532429066, 10.3385430478]
19300       [-6556.74396227, 346.582769726, 10.3292291367]
19301       [-6557.03322125, 346.633069145, 10.3196543607]
19302       [-6557.32237289, 346.683385162, 10.3097966366]
19303         [-6557.6113905, 346.733711011, 10.299717906]
19304       [-6557.88280959, 346.781571086, 10.2717173768]
19305       [-6558.17119715, 346.831885188, 10.2612948396]
19306       [-6558.45936159, 346.882190362, 10.2510659486]
19307        [-6558.74739514, 346.93246882, 10.2410033815]
19308       [-6559.03529201, 346.982718654, 10.2310903107]
19309        [-6559.3230035, 347.032939052, 10.2214476251]
19310       [-6559.61055472, 347.083193442, 10.2120771137]
19311       [-6559.89796066, 347.133431115, 10.2028943285]
19312       [-6560.18513363, 347.183735661, 10.1940061954]
19313       [-6560.47215213, 347.234045085, 10.1851663664]
19314       [-6560.75892966, 347.284267374, 10.1764241061]
19315        [-6561.04556425, 347.334491692, 10.167743774]
19316       [-6561.33204877, 347.384615018, 10.1591036761]
19317       [-6561.61833655, 347.434741088, 10.1503113468]
Name: pos, Length: 19318, dtype: object

In [203]:
x,y,z,w = ego.ori[0]

In [212]:
def f2e(f):
    x,y,z,w = f
    rol = np.arctan2(2*(w*x + y*z), 1 - 2*(x**2 + y**2))
    yaw = np.arcsin(2 * (w*y - z*x))
    pit = np.arctan2(2*(w*z + x*y), 1 - 2*(y**2 + z**2))
    return [rol, yaw, pit]

ori = ego.ori.apply(f2e)

In [242]:
obs.iloc[2][:]

time                                                                    0.4589
obstacles[0].position            [62.11839294433594, -10.380525588989258, 0.0]
obstacles[0].velocity          [-15.799999237060547, 0.10999999940395355, 0.0]
obstacles[0].shape_params    (62.11839294433594, -10.380525588989258, 0.461...
obstacles[0].acceleration                                      [0.0, 0.0, 0.0]
Unnamed: 7                      [104.21891021728516, -2.0597803592681885, 0.0]
Unnamed: 8                     [3.009999990463257, -0.019999999552965164, 0.0]
Unnamed: 9                   (104.21891021728516, -2.0597803592681885, 0.20...
Unnamed: 10                                                    [0.0, 0.0, 0.0]
Unnamed: 11                     [-125.48536682128906, -2.274958372116089, 0.0]
Unnamed: 12                      [-5.799999713897705, 0.5199999809265137, 0.0]
Unnamed: 13                  (-125.48536682128906, -2.274958372116089, 0.35...
Unnamed: 14                                                    [0.0, 0.0, 0.0]
Unnamed: 15                      [-17.69972038269043, -8.096088409423828, 0.0]
Unnamed: 16                      [-6.789999961853027, 0.4099999964237213, 0.0]
Unnamed: 17                  (-17.69972038269043, -8.096088409423828, 6.197...
Unnamed: 18                                                    [0.0, 0.0, 0.0]
Unnamed: 19                     [-62.23979949951172, -2.9910669326782227, 0.0]
Unnamed: 20                      [1.3700000047683716, 0.8100000023841858, 0.0]
Unnamed: 21                  (-62.23979949951172, -2.9910669326782227, 3.55...
Unnamed: 22                                                    [0.0, 0.0, 0.0]
Unnamed: 23                        [76.66107177734375, 2.896742105484009, 0.0]
Unnamed: 24                    [-2.919999837875366, -0.19999998807907104, 0.0]
Unnamed: 25                  (76.66107177734375, 2.896742105484009, 0.20000...
Unnamed: 26                                                    [0.0, 0.0, 0.0]
Unnamed: 27                       [94.29608154296875, 5.7227935791015625, 0.0]
Unnamed: 28                      [2.419999837875366, -1.3799999952316284, 0.0]
Unnamed: 29                  (94.29608154296875, 5.7227935791015625, 0.2000...
Unnamed: 30                                                    [0.0, 0.0, 0.0]
Unnamed: 31                      [84.9303207397461, -0.31450581550598145, 0.0]
                                                   ...
Unnamed: 49                                                                NaN
Unnamed: 50                                                                NaN
Unnamed: 51                                                                NaN
Unnamed: 52                                                                NaN
Unnamed: 53                                                                NaN
Unnamed: 54                                                                NaN
Unnamed: 55                                                                NaN
Unnamed: 56                                                                NaN
Unnamed: 57                                                                NaN
Unnamed: 58                                                                NaN
Unnamed: 59                                                                NaN
Unnamed: 60                                                                NaN
Unnamed: 61                                                                NaN
Unnamed: 62                                                                NaN
Unnamed: 63                                                                NaN
Unnamed: 64                                                                NaN
Unnamed: 65                                                                NaN
Unnamed: 66                                                                NaN
Unnamed: 67                                                                NaN
Unnamed: 68                                                                NaN
Unnamed: 69                                                                NaN
Unnamed: 70                                                                NaN
Unnamed: 71                                                                NaN
Unnamed: 72                                                                NaN
Unnamed: 73                                                                NaN
Unnamed: 74                                                                NaN
Unnamed: 75                                                                NaN
Unnamed: 76                                                                NaN
Unnamed: 77                                                                NaN
Unnamed: 78                                                                NaN
Name: 14, Length: 77, dtype: object

In [219]:
obs = pd.read_csv('2018-12-04-10-59-21-obstacles.csv',low_memory=False)
obs = obs.rename(index=str, columns={"header.stamp.secs": "s", "header.stamp.nsecs": "ns"})
obs.s = list(map(int, obs['s']))
obs.ns = list(map(int, obs['ns']))
obs.time = obs.apply(lambda x: x.s - obs.s[0] + x.ns/1e9 , axis=1)
obs.iloc[:,0:15]
obs = obs.drop(['s','ns'],axis=1)
obs = obs[6:]

In [231]:
obs.head()

,time,obstacles[0].position,obstacles[0].velocity,obstacles[0].shape_params,obstacles[0].acceleration,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,...,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78
12,0.4189,"[62.750728607177734, -10.38479995727539, 0.0]","[-15.819999694824219, 0.10999999940395355, 0.0]","(62.750728607177734, -10.38479995727539, 0.447...","[0.0, 0.0, 0.0]","[104.0985107421875, -2.0589804649353027, 0.0]","[3.009999990463257, -0.019999999552965164, 0.0]","(104.0985107421875, -2.0589804649353027, 0.200...","[0.0, 0.0, 0.0]","[-125.25420379638672, -2.2956326007843018, 0.0]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0.4389,"[62.750728607177734, -10.38479995727539, 0.0]","[-15.819999694824219, 0.10999999940395355, 0.0]","(62.750728607177734, -10.38479995727539, 0.447...","[0.0, 0.0, 0.0]","[104.1587142944336, -2.059380531311035, 0.0]","[3.009999990463257, -0.019999999552965164, 0.0]","(104.1587142944336, -2.059380531311035, 0.2000...","[0.0, 0.0, 0.0]","[-125.37060546875, -2.2852327823638916, 0.0]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,0.4589,"[62.11839294433594, -10.380525588989258, 0.0]","[-15.799999237060547, 0.10999999940395355, 0.0]","(62.11839294433594, -10.380525588989258, 0.461...","[0.0, 0.0, 0.0]","[104.21891021728516, -2.0597803592681885, 0.0]","[3.009999990463257, -0.019999999552965164, 0.0]","(104.21891021728516, -2.0597803592681885, 0.20...","[0.0, 0.0, 0.0]","[-125.48536682128906, -2.274958372116089, 0.0]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0.4789,"[62.11839294433594, -10.380525588989258, 0.0]","[-15.799999237060547, 0.10999999940395355, 0.0]","(62.11839294433594, -10.380525588989258, 0.461...","[0.0, 0.0, 0.0]","[104.27910614013672, -2.060180425643921, 0.0]","[3.009999990463257, -0.019999999552965164, 0.0]","(104.27910614013672, -2.060180425643921, 0.200...","[0.0, 0.0, 0.0]","[-125.60136413574219, -2.2645583152770996, 0.0]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,0.4989,"[61.49392318725586, -10.367344856262207, 0.0]","[-15.789999961853027, 0.05999999865889549, 0.0]","(61.49392318725586, -10.367344856262207, 0.491...","[0.0, 0.0, 0.0]","[104.33930969238281, -2.0605804920196533, 0.0]","[3.009999990463257, -0.019999999552965164, 0.0]","(104.33930969238281, -2.0605804920196533, 0.20...","[0.0, 0.0, 0.0]","[-125.71736145019531, -2.2541582584381104, 0.0]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [233]:
print(obs.iloc[0, 3])
print(obs.iloc[1, 3])
print(obs.iloc[2, 3])
print(obs.iloc[33, 3])
print(obs.iloc[400, 3])
print(obs.iloc[5000, 3])
print(obs.iloc[10000, 3])

(62.750728607177734, -10.38479995727539, 0.4472367465496063, 1.6641072034835815, 0.16167700290679932)
(62.750728607177734, -10.38479995727539, 0.4472367465496063, 1.6641072034835815, 0.16167700290679932)
(62.11839294433594, -10.380525588989258, 0.4619572162628174, 1.6600804328918457, 0.17060266435146332)
(52.50381851196289, -10.273676872253418, 0.21351733803749084, 1.6168413162231445, 0.20547446608543396)
(-50.518287658691406, -8.538501739501953, 0.29572585225105286, 1.067048192024231, 0.5368262529373169)
(111.03313446044922, 2.606583833694458, 0.20000000298023224, 0.9032450914382935, -0.00274209538474679)
(-99.54103088378906, -8.44809341430664, 0.20000000298023224, 1.0418217182159424, 0.00805215910077095)

In [216]:
ego.time[:30]

0     0.3089
1     0.3289
2     0.3489
3     0.3689
4     0.3889
5     0.4089
6     0.4289
7     0.4489
8     0.4689
9     0.4889
10    0.5089
11    0.5289
12    0.5489
13    0.5689
14    0.5889
15    0.6089
16    0.6289
17    0.6489
18    0.6689
19    0.6889
20    0.7089
21    0.7289
22    0.7489
23    0.7689
24    0.7889
25    0.8089
26    0.8289
27    0.8489
28    0.8689
29    0.8889
Name: time, dtype: float64

In [172]:
idx = np.range(1,len(obs.iloc))

list(map(float, obs.iloc[1,2][1:-1].split(',')))

[-15.880000114440918, 0.12999999523162842, 0.0]

In [163]:
def convert(x):
    return x
convert(obs[0,:])
# obs = obs.apply(convert, axis=1)

TypeError: unhashable type: 'slice'

In [159]:
obs.iloc[:5,0:10]

,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,"[0.0, 0.0, 0.0]","[-15.78472900390625, -8.234051704406738, 0.0]","[-6.889999866485596, 0.429999977350235, 0.0]","(-15.78472900390625, -8.234051704406738, 6.195...","[0.0, 0.0, 0.0]","[-62.71331024169922, -3.1679811477661133, 0.0]","[0.5699999928474426, 1.3799999952316284, 0.0]","(-62.71331024169922, -3.1679811477661133, 3.55...","[0.0, 0.0, 0.0]","[77.4796371459961, 2.9430453777313232, 0.0]"
1,"[0.0, 0.0, 0.0]","[-123.9710464477539, -2.3895788192749023, 0.0]","[-5.87999963760376, 0.4899999797344208, 0.0]","(-123.9710464477539, -2.3895788192749023, 0.35...","[0.0, 0.0, 0.0]","[-15.922529220581055, -8.225452423095703, 0.0]","[-6.889999866485596, 0.429999977350235, 0.0]","(-15.922529220581055, -8.225452423095703, 6.19...","[0.0, 0.0, 0.0]","[-62.70191192626953, -3.140381336212158, 0.0]"
2,"[0.0, 0.0, 0.0]","[-16.06155776977539, -8.215229988098145, 0.0]","[-6.87999963760376, 0.41999998688697815, 0.0]","(-16.06155776977539, -8.215229988098145, 6.195...","[0.0, 0.0, 0.0]","[-62.65477752685547, -3.121245861053467, 0.0]","[0.6800000071525574, 1.409999966621399, 0.0]","(-62.65477752685547, -3.121245861053467, 3.557...","[0.0, 0.0, 0.0]","[77.36029052734375, 2.942004680633545, 0.0]"
3,"[0.0, 0.0, 0.0]","[-16.193632125854492, -8.203813552856445, 0.0]","[-6.859999656677246, 0.429999977350235, 0.0]","(-16.193632125854492, -8.203813552856445, 6.19...","[0.0, 0.0, 0.0]","[-62.612884521484375, -3.1096227169036865, 0.0]","[0.7699999809265137, 1.3899999856948853, 0.0]","(-62.612884521484375, -3.1096227169036865, 3.5...","[0.0, 0.0, 0.0]","[77.30317687988281, 2.9324288368225098, 0.0]"
4,"[0.0, 0.0, 0.0]","[-16.33083152770996, -8.195213317871094, 0.0]","[-6.859999656677246, 0.429999977350235, 0.0]","(-16.33083152770996, -8.195213317871094, 6.195...","[0.0, 0.0, 0.0]","[-62.59748840332031, -3.081822633743286, 0.0]","[0.7699999809265137, 1.3899999856948853, 0.0]","(-62.59748840332031, -3.081822633743286, 3.557...","[0.0, 0.0, 0.0]","[77.24297332763672, 2.9298288822174072, 0.0]"